name: Deploy to target

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clone or Update Source Repository
        shell: cmd
        run: |
          if exist sourceGithubAction\.git (
            echo Repository already exists. Fetching latest changes...
            cd sourceGithubAction
            git checkout main
            git pull --ff-only origin main
          ) else (
            echo Cloning repository...
            git clone https://x-access-token:${{ secrets.PAT }}@github.com/ducvubuihong25102000/sourceGithubAction.git sourceGithubAction
          )
      - name: Set Up Source Repository
        shell: cmd
        run: |
          cd sourceGithubAction
          git config user.name "Vũ Bùi Hồng Đức"
          git config user.email "ducvubuihong25102000@gmail.com"

      - name: Push Changes to Target Repository
        shell: cmd
        run: |
          pwd
          cd sourceGithubAction
          pwd
          git remote | findstr uat >nul || git remote add uat https://x-access-token:${{ secrets.PAT }}@github.com/ducvubuihong25102000/targetGithubAction.git
          git push uat main --force
        env:
          GH_TOKEN: ${{ secrets.PAT }}
